config/routes.rb
Rails.application.routes.draw do
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
  get "about", to: "projects#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many_attached :mobile_images
    has_many_attached :desktop_images

    def small
      return self.images.variant(resize: '300x300').processed
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def about
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end
  def edit
    @project = Project.find(params[:id])
  end
  def update
    if @project = Project.update(project_params)
      redirect_to @project, notice: "successfully updated"
    else render 'edit'
    end
  end
end

private

def project_params
  params.require(:project).permit(:name, :caption, mobile_images: [], desktop_images: [])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/landing_pages/index.html.erb
<h1>David Berko</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="logo">
    <%= link_to "DMB Web Development", root_path %>
  </div>
  <nav>
    <div id="nav_container">
      <ul>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "Github", "https://github.com/davidberko" %>
        <li>
          <%= link_to "Stack Overflow", "https://stackoverflow.com/users/10140583/dmberko11?tab=profile" %>
        </li>
        <li>
          <%= link_to "Resume/CV", "https://docs.google.com/document/d/1NNXNmKbanYayx5rqFgUpONAiOwxZ0JArbasewo2d5kE/edit?usp=sharing" %>
        </li>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: @project) do |f| %>
<div id="new_project_form">
  <div id="form_field">
    <%= f.label :link %>
    <%= f.text_field :link %><br />
  </div>
  <div id="form_field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
  </div>
  <div id="form_field">
    <%= f.file_field :mobile_images, multiple: true %><br />
    <%= f.file_field :desktop_images, multiple: true %><br />
    <%= f.label :caption %><br />
  </div>
  <div id="form_field">
    <%= f.text_area :caption %><br />
  </div>
  <div id="submit_field">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/projects/about.html.erb
<h2 id="story_header">My Developer's Story</h2>

<div id="story_container">
  <p id="story_text">I didn't have a background in IT until I was in my 20s. I think I came across an internship opportunity
  that I saw on Facebook and applied. A few weeks later I moved across the country from Indiana to Texas to try something
  new. It was overwhelming to say the least. I didn't even know what a variable was. But they were patient with me and
  before long I was building full-stack web apps with Ruby on Rails, HTML, and CSS. I got laid off maybe five months into
  what was supposed to be an 18 month term. I thought it was because of my performance shortcomings being so wet behind the
  ears that I was. Come to find out the truth of the matter was the company was downsizing and decided to let go their newest batch
  of paid interns to right the ship and get back on track financially. I could understand that. It still sucked. However, from
  what I learned there I knew that one day I would be doing this as a web developer. Some way somehow I would make it as a mostly self-
  taught programmer and have an awesome success story to tell. </p>

  <p id="paragraph_2">After maybe a six year hiatus post-internship I finally got back to developing again after I decided in that time frame to do the college thing and get a degree and see where life took me.
  I had much regret for wasting so much time on a dead-end I then returned to my computer and relearned everything. A friend of mine who knew my background happened to be launching his own business
  and he needed a website. He asked me if this was something I could do for him. I said sure! Not knowing what I was getting myself into
  since it had been so long since I had coded and wasn't sure if I'd be up to the task. Well a few months later I had a nice little website for him
  with an admin section as well. He was pleased and that sparked the motivation for me that I could get back on track as a developer and make this a career.
  Since then (late 2018) I have built a couple project apps and have tidied up a small portfolio. My mission has been to really learn a technology stack like Rails, Ruby, Javascript,
  HTML, and CSS for web apps. 2019 I hope to quit driving for Uber and make it a go at being a Rails developer. Hope you enjoyed hearing about my journey.</p>
  <p id="signature">
    David Berko
  </p>
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 id="headline">What I've Been Up To</h1>

<body>
  <div id="div">
    <p>
    </p>
  </div>
  <% @projects.each do |p| %>
    <div id="caption_details">
      <b><%= p.name %><b>
      <p class="project_caption"><%= p.caption %></p>
      See the repo on <a href="<%= p.link %>"><%= image_tag("icons8-github-104.png", style: "width:50px;height:50px;") %></a>
    </div>



  <div id="project_container">
    <h2 id="screenshot_header">Screenshots</h2>
    <h3 id="mobile_header">Mobile</h3>
    <div id="mobile_image_div">
      <% p.mobile_images.each do |mi| %>
      <%= image_tag mi.variant(resize: "400x400"), class: "m_img" %><br/ >
      <% end %>
    </div>

    <h3 id="desktop_header">Desktop</h3>
      <div id="destop_image_div" onclick="revealImage();">
        <% p.desktop_images.each do |di| %>
        <%= image_tag di.variant(resize: "500x500"), class: "d_img" %><br />
        <% end %>
    </div>
  </div>
  <% end %>

</body>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html>

<body>
<h1><%= @project.name %></h1>
<% @project.desktop_images.each do |image| %>

<% end %>
<%= @project.caption %>

<%= link_to "edit", edit_project_path(@project) %>


</body>
</html>